import Foundation

@main struct VoiceTurnCheck {
    static func main() {
        var turn = VoiceTurn()
        precondition(!turn.interrupt(busy: false))
        precondition(turn.interrupt(busy: true))
        precondition(!turn.interrupt(busy: true))
        turn.queue("Actually")
        turn.queue("make it tomorrow")
        precondition(turn.interrupted)
        precondition(turn.ready() == "Actually make it tomorrow")
        precondition(!turn.interrupted && turn.pending == nil)
        precondition(turn.ready() == nil)
        precondition(turn.interrupt(busy: true))
        turn.queue("discard this when voice ends")
        turn.discardPending()
        precondition(turn.ready() == nil)
        // A provisional recognition must not consume the cancellation request.
        turn.pausePlayback(busy: true)
        precondition(turn.interrupted && turn.pending == nil)
        precondition(turn.ready() == nil)
        precondition(!turn.interrupted)
        turn.pausePlayback(busy: true)
        turn.pausePlayback(busy: true)
        turn.queue("What is the bicycle name?")
        precondition(turn.interrupt(busy: true))
        precondition(!turn.interrupt(busy: true))
        precondition(turn.ready() == "What is the bicycle name?")
        let now = Date(timeIntervalSince1970: 100)
        var echo = PlaybackEcho()
        precondition(!echo.matches("Hello", now: now))
        echo.record("Of course. What would you like to do today?", now: now)
        precondition(echo.matches("Of course", now: now))
        precondition(echo.matches("what would you like to do today", now: now))
        precondition(echo.matches("what would you like to go today", now: now))
        precondition(!echo.matches("Stop", now: now))
        precondition(!echo.matches("Actually I want to talk about tomorrow", now: now))
        precondition(echo.suppressDuringPlayback("Of", final: false, now: now))
        precondition(echo.suppressDuringPlayback("What would", final: false, now: now))
        precondition(echo.suppressDuringPlayback("what could you", final: false, now: now))
        precondition(!echo.suppressDuringPlayback("stop", final: false, now: now))
        precondition(!echo.suppressDuringPlayback("Actually tomorrow works better", final: false, now: now))
        echo.finished(now: now)
        precondition(!echo.suppressDuringPlayback("Yes", final: false, now: now.addingTimeInterval(2)))
        precondition(echo.matches("Of course", now: now.addingTimeInterval(1)))
        precondition(!echo.matches("Of course", now: now.addingTimeInterval(3)))
        echo.resumed()
        precondition(echo.matches("Of course", now: now.addingTimeInterval(3)))
        echo.finished(now: now)
        echo.record("Tomorrow is free", now: now.addingTimeInterval(4))
        precondition(!echo.matches("Of course", now: now.addingTimeInterval(4)))
        precondition(echo.matches("Tomorrow is free", now: now.addingTimeInterval(4)))
        precondition(voicePause("Hello.") == 1.0)
        precondition(voicePause("I want to explain something because...") == 1.8)
        precondition(voicePause("How quickly") == 1.8)
        precondition(voicePause(String(repeating: "more words ", count: 12)) == 1.65)
        var longReply = PlaybackEcho()
        longReply.record("Here is the beginning of the reply you can still hear", now: now)
        longReply.record(String(repeating: "additional details for later playback ", count: 25), now: now)
        precondition(longReply.matches("Here is the beginning of the reply", now: now))
        var interruption = PlaybackInterruption()
        precondition(!interruption.accept("garbled words", guarded: true, final: true, now: now))
        precondition(!interruption.accept("Actually tomorrow is much better", guarded: true, final: false, now: now))
        precondition(interruption.accept("Actually tomorrow is much better", guarded: true, final: false, now: now.addingTimeInterval(0.4)))
        precondition(interruption.accept("stop", guarded: true, final: false, now: now))
        precondition(interruption.accept("Yes", guarded: false, final: true, now: now))
        let audioURL = URL(string: "data:audio/mp4;base64,YXVkaW8=")!
        precondition(Data(base64Encoded: String(audioURL.absoluteString.dropFirst("data:audio/mp4;base64,".count))) == Data("audio".utf8))
        var incomplete = "This is still"
        precondition(nextSpeechChunk(&incomplete, flush: false) == nil)
        precondition(incomplete == "This is still")
        let original = String(repeating: "A longer spoken reply has several words ", count: 8) + "."
        var buffer = original
        var chunks: [String] = []
        while let chunk = nextSpeechChunk(&buffer, flush: true) { chunks.append(chunk) }
        precondition(chunks.first!.count <= 100)
        precondition(chunks.joined() == original)
        precondition(nextSpeechChunk(&incomplete, flush: true) == "This is still")
        precondition(incomplete.isEmpty)
        print("Voice interruption preserves speech and cancels each turn once.")
    }
}
